// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ZCdJ_ZS0_bQ3f6QIqT3yIeZ_kHu58JA',
    appId: '1:525566613980:web:eb182252810ab7e0469719',
    messagingSenderId: '525566613980',
    projectId: 'fir-mychat-c5734',
    authDomain: 'fir-mychat-c5734.firebaseapp.com',
    storageBucket: 'fir-mychat-c5734.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0PaiMLVAYBx4gUO1AB2uoyWn9_-0SOcA',
    appId: '1:525566613980:android:0de21cd3f6376ac3469719',
    messagingSenderId: '525566613980',
    projectId: 'fir-mychat-c5734',
    storageBucket: 'fir-mychat-c5734.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEiLXzoN-AgjWwd6M0qpu4zAAGbd4DDOQ',
    appId: '1:525566613980:ios:bde608564de90e6a469719',
    messagingSenderId: '525566613980',
    projectId: 'fir-mychat-c5734',
    storageBucket: 'fir-mychat-c5734.appspot.com',
    iosClientId: '525566613980-c4o2ocbfkbeql0suf3892rkfib9jrace.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEiLXzoN-AgjWwd6M0qpu4zAAGbd4DDOQ',
    appId: '1:525566613980:ios:bde608564de90e6a469719',
    messagingSenderId: '525566613980',
    projectId: 'fir-mychat-c5734',
    storageBucket: 'fir-mychat-c5734.appspot.com',
    iosClientId: '525566613980-c4o2ocbfkbeql0suf3892rkfib9jrace.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
